# config/services_acl.toml

[acl.services.auth-service]
service_id = "auth-service"
secret = "super-long-random-secret-for-auth-service-hmac-64-bytes"
allowed_access = [
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PrivateKey" },
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PublicKey" },
    { target_service = "shared-jwt", algorithm = "Ed25519", access_level = "PrivateKey" },

    { target_service = "docs-passport", algorithm = "AES256GCM", access_level = "SecretKey" },

    { target_service = "internal-communication-hmac", algorithm = "HmacSha256", access_level = "SecretKey" }
]

[acl.services.gateway-service]
service_id = "gateway-service"
secret = "super-long-random-secret-for-gateway-service-hmac-64-bytes"
allowed_access = [
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PublicKey" },
    { target_service = "shared-jwt", algorithm = "Ed25519", access_level = "PublicKey" },

    { target_service = "internal-communication-hmac", algorithm = "HmacSha256", access_level = "SecretKey" }
]

[acl.services.citizen-docs-service]
service_id = "citizen-docs-service"
secret = "super-long-random-secret-for-docs-service-hmac-64-bytes"
allowed_access = [
    # Klucze symetryczne do szyfrowania danych (AES-256)
    { target_service = "docs-id-cards", algorithm = "AES256GCM", access_level = "SecretKey" },
    { target_service = "docs-driver-license", algorithm = "AES256GCM", access_level = "SecretKey" },
    { target_service = "docs-passport", algorithm = "AES256GCM", access_level = "SecretKey" },

    { target_service = "internal-communication-hmac", algorithm = "HmacSha256", access_level = "SecretKey" }
]