# config/services_acl.toml

[acl.services.auth-service]
service_id = "auth-service"
secret = "super-long-random-secret-for-auth-service-hmac-64-bytes"
allowed_access = [
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PrivateKey" },
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PublicKey" },
    { target_service = "shared-jwt", algorithm = "Ed25519", access_level = "PrivateKey" }
]

[acl.services.gateway-service]
service_id = "gateway-service"
secret = "super-long-random-secret-for-gateway-service-hmac-64-bytes"
allowed_access = [
    { target_service = "auth-service", algorithm = "Ed25519", access_level = "PublicKey" },
    { target_service = "shared-jwt", algorithm = "Ed25519", access_level = "PublicKey" }
]